#!/bin/bash
PATH=./node_modules/.bin:$PATH

###############################################################################
# ACTIONS

function init {
  sudo npm install -g truffle solc
  cd deploy
  npm install
}

function test {
  truffle test
}

function build {
  solcjs --bin --abi --optimize -o ./build ./contracts/*.sol
}

function deploy {
  build
  node deploy
}

###############################################################################
# DEFAULT => HELP

function default {
  echo "$0 <task> <args>"
  echo
  echo "Available tasks:"
  compgen -A function | cat -n
}


TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
